//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendEase.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DostawaTowary
    {
        public int IDTowaru { get; set; }
        public int IDZamowienieZewnetrzne { get; set; }
        public int Ilosc { get; set; }
        public string Opis { get; set; }
        public Nullable<System.DateTime> DataWaznosci { get; set; }
    
        public virtual Towary Towary { get; set; }
        public virtual ZamowieniaZewnetrzne ZamowieniaZewnetrzne { get; set; }
    }
}
