//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendEase.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maszyny
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Maszyny()
        {
            this.MaszynaTowary = new HashSet<MaszynaTowary>();
            this.Transakcje = new HashSet<Transakcje>();
            this.Wizyty = new HashSet<Wizyty>();
            this.Lokalizacje = new HashSet<Lokalizacje>();
            this.Trasy = new HashSet<Trasy>();
        }
    
        public string NumerMaszyny { get; set; }
        public int IDTypMaszyny { get; set; }
        public string NumerSeryjny { get; set; }
        public System.DateTime RokProdukcji { get; set; }
        public string Opis { get; set; }
        public Nullable<System.DateTime> DataMontazu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaszynaTowary> MaszynaTowary { get; set; }
        public virtual TypyMaszyn TypyMaszyn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transakcje> Transakcje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wizyty> Wizyty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lokalizacje> Lokalizacje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trasy> Trasy { get; set; }
    }
}
