//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendEase.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VendingEntities : DbContext
    {
        public VendingEntities()
            : base("name=VendingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DostawaTowary> DostawaTowary { get; set; }
        public virtual DbSet<Dostawcy> Dostawcy { get; set; }
        public virtual DbSet<Faktury> Faktury { get; set; }
        public virtual DbSet<Lokalizacje> Lokalizacje { get; set; }
        public virtual DbSet<MagazynTowary> MagazynTowary { get; set; }
        public virtual DbSet<Magazyny> Magazyny { get; set; }
        public virtual DbSet<MaszynaTowary> MaszynaTowary { get; set; }
        public virtual DbSet<Maszyny> Maszyny { get; set; }
        public virtual DbSet<Pojazdy> Pojazdy { get; set; }
        public virtual DbSet<Pracownicy> Pracownicy { get; set; }
        public virtual DbSet<PracownikTowary> PracownikTowary { get; set; }
        public virtual DbSet<StanowiskaPracy> StanowiskaPracy { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Towary> Towary { get; set; }
        public virtual DbSet<Transakcje> Transakcje { get; set; }
        public virtual DbSet<Trasy> Trasy { get; set; }
        public virtual DbSet<TypyMaszyn> TypyMaszyn { get; set; }
        public virtual DbSet<Warsztaty> Warsztaty { get; set; }
        public virtual DbSet<Wizyty> Wizyty { get; set; }
        public virtual DbSet<Zamowienia> Zamowienia { get; set; }
        public virtual DbSet<ZamowieniaZewnetrzne> ZamowieniaZewnetrzne { get; set; }
    }
}
