//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendEase.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pojazdy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pojazdy()
        {
            this.Pracownicy = new HashSet<Pracownicy>();
        }
    
        public int IDPojazdu { get; set; }
        public string Marka { get; set; }
        public string NumerRejestracyjny { get; set; }
        public System.DateTime DataPrzegladu { get; set; }
        public System.DateTime DataUbezpieczenia { get; set; }
        public Nullable<int> IDWarsztatu { get; set; }
        public string Opis { get; set; }
        public string Usterki { get; set; }
    
        public virtual Warsztaty Warsztaty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pracownicy> Pracownicy { get; set; }
    }
}
