//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendEase.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pracownicy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pracownicy()
        {
            this.PracownikTowary = new HashSet<PracownikTowary>();
            this.Wizyty = new HashSet<Wizyty>();
            this.Zamowienia = new HashSet<Zamowienia>();
        }
    
        public int IDPracownika { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public int IDStanowiskaPracy { get; set; }
        public decimal Pensja { get; set; }
        public System.DateTime DataZatrudnienia { get; set; }
        public Nullable<int> IDPojazdu { get; set; }
        public Nullable<int> IDTrasy { get; set; }
        public string Opis { get; set; }
    
        public virtual Pojazdy Pojazdy { get; set; }
        public virtual StanowiskaPracy StanowiskaPracy { get; set; }
        public virtual Trasy Trasy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PracownikTowary> PracownikTowary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wizyty> Wizyty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zamowienia> Zamowienia { get; set; }
    }
}
