//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendEase.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PracownikTowary
    {
        public int IDPracownika { get; set; }
        public int IDTowaru { get; set; }
        public int Stan { get; set; }
        public string Opis { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
    
        public virtual Pracownicy Pracownicy { get; set; }
        public virtual Towary Towary { get; set; }
    }
}
