//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendEase.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StanowiskaPracy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StanowiskaPracy()
        {
            this.Pracownicy = new HashSet<Pracownicy>();
        }
    
        public int IDStanowiskaPracy { get; set; }
        public string NazwaStanowiska { get; set; }
        public string Dzial { get; set; }
        public int WymaganeDoswiadczenie { get; set; }
        public string Status { get; set; }
        public string Opis { get; set; }
        public Nullable<System.DateTime> DataUtworzenia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pracownicy> Pracownicy { get; set; }
    }
}
