//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendEase.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypyMaszyn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TypyMaszyn()
        {
            this.Maszyny = new HashSet<Maszyny>();
        }
    
        public int IDTypMaszyny { get; set; }
        public string Typ { get; set; }
        public string Producent { get; set; }
        public string Model { get; set; }
        public string Opis { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maszyny> Maszyny { get; set; }
    }
}
