//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendEase.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wizyty
    {
        public int IDWizyty { get; set; }
        public int IDPracownika { get; set; }
        public string NumerMaszyny { get; set; }
        public System.DateTime Data { get; set; }
        public string TypWizyty { get; set; }
        public string Opis { get; set; }
    
        public virtual Maszyny Maszyny { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
    }
}
